name: Deploy(Beta)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sign in to GCP
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/175809265292/locations/global/workloadIdentityPools/github/providers/github-api'
          service_account: 'naddal@hancomac.iam.gserviceaccount.com'

      - name: Use docker login action
        uses: 'docker/login-action@v3'
        with:
          registry: 'asia.gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0

      - name: Build Dockerfile
        run: docker build -t asia.gcr.io/hancomac/naddal:latest .
        working-directory: ./server

      - name: Push Docker Image
        run: docker push asia.gcr.io/hancomac/naddal:latest